spring:
  application:
    name: gateway-service
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:
  cloud:
    nacos:
      discovery:
        server-addr: 125.124.41.180:8848
    gateway:
      discovery:
        locator:
          enabled: false

    sleuth:
      sampler:
        probability: 1