spring:
  h2:
    console:
      path: /h2-console #??h2 web???????
      enabled: true #??h2 web??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql

mybatis:
#  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:/mybatis-config.xml
